# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class SkimPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sender: int
    balance0: int
    balance1: int
    reserve0: int
    reserve1: int
    amount0: int
    amount1: int
    factory_address: int
    block_timestamp: int
