# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class SwapPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sender: int
    amount0_in: int
    amount1_in: int
    amount0_out: int
    amount1_out: int
    balance0: int
    balance1: int
    reserve0: int
    reserve1: int
    factory_address: int
    block_timestamp: int
