# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class SyncPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    balance0: int
    balance1: int
    reserve0: int
    reserve1: int
    price_0_cumulative_last: int
    price_1_cumulative_last: int
    factory_address: int
    block_timestamp: int
