# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FactoryInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    factory_address: int
    owner: int
    fee_to: int
    pair_contract_class_hash: int
    block_timestamp: int
