# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FeesReceiverUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    previous_fee_to: int
    new_fee_to: int
    factory_address: int
    block_timestamp: int
