# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PairCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token0: int
    token1: int
    pair: int
    total_pairs: int
    pair_contract_class_hash: int
    factory_address: int
    block_timestamp: int
