# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PowerplantInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    powerplant: int
    owner: int
    reactor_class_hash: int
    block_timestamp: int
