# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ReactorCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reactor: int
    lp_token: int
    powerplant: int
    penalty_duration: int
    withdraw_penalty: int
    multiplier: int
    penalty_receiver: int
    reactor_index: int
    reactor_count: int
    block_timestamp: int
