# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ERC20RecoveredPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_address: int
    token_amount: int
    to: int
    block_timestamp: int
