# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class HarvestPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_address: int
    reward_token: int
    reward_amount: int
    total_staked: int
    user_staked: int
    reward_per_token_stored: int
    block_timestamp: int
