# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PenaltyReceiverUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    previous_receiver: int
    new_receiver: int
    block_timestamp: int
