# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RewardAddedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reward_token: int
    reward_amount: int
    reward_rate: int
    reward_duration: int
    period_finish: int
    reward_per_token_stored: int
    unallocated_rewards: int
    block_timestamp: int
    rewarder: int
