# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class WithdrawPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_address: int
    staked_amount: int
    penalty_amount: int
    total_staked: int
    user_staked: int
    penalty_end_time: int
    block_timestamp: int
